apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-storm-ui
spec:
  replicas: 1
  selector:
    storm: ui
  template:
    metadata:
      labels:
        storm: ui
        app: storm
    spec:
      containers:
      - name: zookeeper
        image: thegillis/storm-cluster:latest
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "ui"
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

