apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-storm-nimbus
spec:
  replicas: 1
  selector:
    storm: nimbus
  template:
    metadata:
      labels:
        storm: nimbus
        app: storm
    spec:
      containers:
      - name: zookeeper
        image: thegillis/storm-cluster:latest
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "nimbus"
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

